version: '3'
services:
  nginx:
    build: nginx/
    ports:
    - 80:80
    links:
    - php
  php:
    build: fpm/
    depends_on:
    - composer
    volumes:
    - ../app:/var/www/html/app
    # - ./fpm/default.php:/var/www/html
    # - ./fpm/oxy:/var/www/html/oxy
  composer:
    image: composer
    volumes:
    - ./fpm/oxy:/app
    command: install
volumes:
  oxy:
  app:
